#!/bin/sh

set -eu

docker build -t "dotenv:${0##*/}" - <<HERE
FROM golang
RUN apt-get update && apt-get install -y vim
RUN go get github.com/joho/godotenv github.com/joho/godotenv/cmd/godotenv
WORKDIR /root
HERE

cid=$(docker create --rm -it "dotenv:${0##*/}" /bin/bash)
docker cp ./ "$cid:/root/"
docker start -ai "$cid"
