#!/bin/sh

set -eu

docker build -t "dotenv:${0##*/}" - <<HERE
FROM buildpack-deps:curl
RUN apt-get update && apt-get install -y vim
RUN curl -sSfL https://raw.githubusercontent.com/dotenv-linter/dotenv-linter/master/install.sh | sh -s
WORKDIR /root
HERE

cid=$(docker create --rm -it "dotenv:${0##*/}" /bin/bash)
docker cp ./ "$cid:/root/"
docker start -ai "$cid"
