#!/bin/sh

set -eu

docker build -t "dotenv:${0##*/}" - <<HERE
FROM node
RUN apt-get update && apt-get install -y vim
RUN npm install -g dotenv dotenv-expand dotenv-safe dotenv-cli
WORKDIR /root
HERE

cid=$(docker create --rm -it "dotenv:${0##*/}" /bin/bash)
docker cp ./ "$cid:/root/"
docker start -ai "$cid"
