#!/bin/sh

set -eu

docker build -t "dotenv:${0##*/}" - <<HERE
FROM ruby
RUN apt-get update && apt-get install -y vim
RUN gem install dotenv
WORKDIR /root
HERE

cid=$(docker create --rm -it "dotenv:${0##*/}" /bin/bash)
docker cp ./ "$cid:/root/"
docker start -ai "$cid"
